version: 2.1
jobs:
    build:
        working_directory: ~/zooplus_appium_task
        docker:
            - image: circleci/openjdk:11-jdk
        steps:
            - checkout
            - run: mvn clean install -DskipTests=true
    regression-test:
        working_directory: ~/zooplus_appium_task
        docker:
            - image: circleci/android:api-29
        steps:
            - checkout
            
            - run:
                name: Install libs for libpulse
                command: |
                        cd
                        sudo apt-get update
                        sudo apt-get install pulseaudio
            - run:
                name: Install Node
                command: |
                    cd
                    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
                    sudo apt install -y nodejs
            - run:
                name: Print Node and NPM Version
                command: |
                    node --version
                    npm --version
            - run: |
                 rm -rf node_modules
                 npm cache clean --force
                 rm -rf package-lock.json
                 
            - run: npm install --save-dev
           
            
            - run:
                name: List Images
                command: sdkmanager --list --verbose | grep system-images
            - run:
                name: Setup Emulator
                command: sdkmanager --install "system-images;android-29;google_apis;arm64-v8a" && echo
                    "no" | avdmanager create avd -n test -k "system-images;android-29;google_apis;arm64-v8a" --force
            - run:
                name: Launch Emulator
                command: |
                    cd ${ANDROID_HOME}/emulator;ls
                    export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
                    emulator -avd test -skin 1080x2220 -no-window -noaudio -no-boot-anim -no-window -accel on
                background: true
                
            - run: |
                 adb wait-for-device
                 adb devices
                 echo "Emulator started"
            
                    
            - run:
                name: Wait emulator
                command: |
                    circle-android wait-for-boot
                    adb shell input keyevent 82
            
            - run:
                name: Install Appium
                command: |
                    cd
                    npm install appium@1.22.0
                    npm audit fix
            - run:
                name: Start Appium
                command: cd ; appium
                background: true
            - run:
                name: Wait Until Appium Boot
                command: sleep 30
            - checkout
            
            - run:
                name: Run Tests
                command: mvn clean test -Dtest.level=regression -Dgroups=regression
            - store_test_results:
                path: target/surefire-reports
            - store_artifacts:
                path: target/surefire-reports
                destination: regression-test-results
workflows:
    build_and_test:
        jobs:
            - build
            - regression-test:
                        requires:
                            - build
